Fix PHP code highlighting and improve content
drunomics/lupus-decoupled-website pull request #85
Opened 2024-12-20 14:50 UTC by vloss3

2025-01-18 03:44 UTC, fago requested changes

2025-01-18 03:44 UTC, fago commented on content/1.get-started/10.how-it-works.md
> +    content?: Object;
we don't want to define content as prop. this is the default slot we are receiving. let's keep the documentation citing the code of the component as shipped with nuxtjs-drupal-ce,  I think the code as ok before.

2025-01-18 03:44 UTC, fago commented on content/5.nuxt/30.render-custom-elements.md
> +const { renderCustomElements } = useDrupalCe()
let's not do this import for brevity. --> let's keep code as shipped with the module

2025-01-20 12:24 UTC, rmuit commented
Merging this on request.

I have not been tightly involved in this repo, but
* I can see the requested changes are implemented;
* I can pretty much judge the other changes and see they are OK / imagine that we want to see them live.

2025-01-20 12:25 UTC, rmuit approved these changes

2025-01-20 12:26 UTC, merged